server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1
  open_api:
    addr: 0.0.0.0:8080
    timeout: 1
postgres:
  hostname: 
  port: 
  user: 
  password: 
  db:
